org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.4-beta
moddev_version=2.0.147
junit_version=5.14.2
fabric_loader_compile_version=0.19.5
fabric_gametest_compile_version=4.0.32+3434d6d95d

mod_id=smart_resource_drops
mod_name=Smart Resource Multiplier
mod_license=MIT
mod_version=1.4.0
mod_group_id=com.chedidandrew
archives_base_name=smart-resource-multiplier-neoforge
