org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
java_version=21
neo_version=21.1.249
moddev_version=2.0.146
junit_version=5.14.2
mod_id=smart_resource_drops
mod_name=Smart Resource Multiplier
mod_license=MIT
mod_version=1.3.0+mc1.21.1
mod_group_id=com.chedidandrew
archives_base_name=smart-resource-multiplier-neoforge
