org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.72
moddev_version=2.0.144

mod_id=smart_resource_drops
mod_name=Smart Resource Multiplier
mod_license=MIT
mod_version=1.2.3
mod_group_id=com.chedidandrew
archives_base_name=smart-resource-multiplier-neoforge
